### ISSUE TITLE
Cannot find this lib in MVN repository

### ISSUE THREAD

**Issue by dang-toan** [Luncher91/A2LParser#25]
Could you please help to check mvn repository again? I cannot find this library in here:
https://mvnrepository.com/search?q=a2lparser

**Comment by Luncher91** [comment]
Unfortunately I did not yet publish the lib to the central maven repository. Alternatively you can configure github as a maven repository and fetch the most recent version from there: https://github.com/Luncher91/A2LParser/packages/960898
Github also provides documentation how to add a package from github to your sources of packages: https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry

I will keep this issue open until I made the package available on mvnrepository.com since that is already on my [roadmap](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry).
