### ISSUE TITLE
cannot read a2l after export with .jar

### ISSUE THREAD

**Issue by 321Oscar** [Luncher91/A2LParser#26]
i use jar a2l to json and then json to a2l without any modifition, but i cannot read new a2l file with jar.
![image](https://user-images.githubusercontent.com/30036385/197952474-e0d34cbb-bdff-4846-80d2-880e2dade52e.png)

 i read a2l with jar
![image](https://user-images.githubusercontent.com/30036385/197952657-7870b0d9-e83c-4210-a612-7577523bb6b2.png)
then i export this Aspa2File with json,then transform json to a2l like this
![image](https://user-images.githubusercontent.com/30036385/197953285-3ee16b0f-72d8-450a-af75-f6abe15ab557.png)

![image](https://user-images.githubusercontent.com/30036385/197953026-5f087800-3d50-49bc-913a-3cbd607df610.png)

finally , i read this new a2l fle , but it seems wrong.
![image](https://user-images.githubusercontent.com/30036385/197953145-7b5a6937-2647-4152-847b-b26c022c6aa6.png)

[Control.zip](https://github.com/Luncher91/A2LParser/files/9866835/Control.zip)

**Comment by 321Oscar** [comment]
i read it by C#

**Comment by Luncher91** [comment]
Hi Oscar,

I am not sure if it is an issue of the older version of the parser but when I parse your A2L the first time it spits out a json but along with an error message:

`java -jar a2lparser-2.5.2-jar-with-dependencies.jar -mj -a2l Control.a2l -o Control.json`
`Line 36@21: mismatched input 'LSB_LAST' expecting {'LITTLE_ENDIAN', 'BIG_ENDIAN', 'MSB_LAST', 'MSB_FIRST'}`
`Line 36@21: Invalid enum value for ByteOrder: LSB_LAST`
`Possible values are [LITTLE_ENDIAN,BIG_ENDIAN,MSB_LAST,MSB_FIRST]`

Fixing that in the A2L makes it possible to parse the json back to A2L without any problems.

If you do not get the mentioned error please try to update your a2lparser since it looks like your are using 2.3.2 and fix the BYTE_ORDER in your A2L.

Kind regards
Andreas

**Comment by 321Oscar** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by 321Oscar** [comment]
> Hi Oscar,
> 
> I am not sure if it is an issue of the older version of the parser but when I parse your A2L the first time it spits out a json but along with an error message:
> 
> `java -jar a2lparser-2.5.2-jar-with-dependencies.jar -mj -a2l Control.a2l -o Control.json` `Line 36@21: mismatched input 'LSB_LAST' expecting {'LITTLE_ENDIAN', 'BIG_ENDIAN', 'MSB_LAST', 'MSB_FIRST'}` `Line 36@21: Invalid enum value for ByteOrder: LSB_LAST` `Possible values are [LITTLE_ENDIAN,BIG_ENDIAN,MSB_LAST,MSB_FIRST]`
> 
> Fixing that in the A2L makes it possible to parse the json back to A2L without any problems.
> 
> If you do not get the mentioned error please try to update your a2lparser since it looks like your are using 2.3.2 and fix the BYTE_ORDER in your A2L.
> 
> Kind regards Andreas

Hi Andreas,
I use 2.5.2 version to transform this a2l file.and also modified the byteorder. But same problem happened. 
![image](https://user-images.githubusercontent.com/30036385/198218636-9adfb322-df6f-45f7-94cc-dc987855fd14.png)

Best wishes
Oscar

**Comment by Luncher91** [comment]
I ran it now with version 2.5.3 and it worked. Can you confirm?

**Comment by 321Oscar** [comment]
> 

Hi Andreas,
Version 2.5.3 solves this problem. Thank you.
Best wishes
Oscar
